import { QUESTIONS, nextTrial, trialKey, summarizeChoices } from './choices.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const API='https://api.alldogs.wtf/upright-api', KEY='upright-feedback-v1';
const vocab=[
 ['unequal-eyes','Unequal apertures','One low blue eye against one tall hooked violet eye. Preserve the inequality while changing the drawing.','mischief-4','Expression demonstrated'],
 ['sideways-gaze','Shared sideways gaze','Move the gaze consistently inside different eye shapes. One eye withholds; the other watches.','mischief-4','Expression demonstrated'],
 ['cheek-mouth','Cheek lifts mouth','Let a contracting cheek pull one mouth corner upward. The tooth grin is optional.','mischief-4','Expression demonstrated; grin may be too explicit'],
 ['bury-recover','Bury and recover','Paint across an old contour, then recover a displaced fragment. Leave evidence of the earlier drawing.','bowie-4','Demonstrated in the accepted cheek'],
 ['broken-color','Broken color return','Carry copper, coral or violet into another passage. Let color connect hair, face and clothing.','bowie-4','Demonstrated in accepted Bowie'],
 ['loaded-deposit','Loaded deposit','A short broad stroke carrying substantial paint. Give it a route through a form so it does not become an isolated pad.','brush-4','Relief demonstrated; composition unresolved'],
 ['exhausted-drag','Exhausted drag','Pull depleted paint across an edge so earlier drawing shows through. Make its ending unlike the loaded marks.','brush-5','Material move demonstrated locally'],
 ['wet-crossing','Wet crossing','Pull flesh or coral through fresh violet before drying. Let the mixed color leave the original patch.','brush-5','Pigment mixing demonstrated; integration unresolved'],
 ['dry-separation','Dry separation','Dry pale underpainting before adding a dark lid or pupil. Use this where you need a clean dark shape.','mischief-4','Resolved the pale bandage effect'],
 ['recovery-line','Interrupted recovery line','A few unequal charcoal or wax fragments recover a form. Leave some features unenclosed.','bowie-4','Demonstrated in accepted Bowie']
];
const experiments=[
 ['A smile made by paint','Keep the sideways gaze. Bury the outlined grin and tooth, then find the mouth in the broken boundary between violet paint and a flesh drag. Does mischief survive without the smile symbol?',['sideways-gaze','wet-crossing','bury-recover']],
 ['A squint made by hair','Keep accepted Bowie’s mouth. Carry a broken copper gesture from temple into the actual blue eye aperture. Dry it, then recover only the lower edge.',['unequal-eyes','exhausted-drag','recovery-line']],
 ['A cheek carried across the face','Move wet interference into the blue eye socket, cheek and mouth corner. Let a flesh pull through violet leave its mixed paint at the lip.',['cheek-mouth','wet-crossing','dry-separation']],
 ['A changed drawing left visible','Shift one cheek inward and rotate the tall eye slightly. Retain fragments of their old positions. No explicit grin or raised brow.',['unequal-eyes','exhausted-drag','bury-recover']]
];
let activeTrial=null, busy=false, lastChoice=null, previousTrial=null, displayed=new Set(), cooldownUntil=0;
let portraits=[],byId={},current=null,filter='Featured',syncing=false,resync=false,connected=false,revision=0;
let state={version:1,reviews:{},pairs:{},attributes:{},recipe:{moves:[],intention:'',updatedAt:0}};
let storageOK=true;
try{const old=JSON.parse(localStorage.getItem(KEY)||'null');if(old&&old.version===1&&old.reviews&&old.pairs&&old.recipe)state=old;}catch{storageOK=false;}
state.attributes ||= {};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function key(){try{return localStorage.getItem('upright_connection_disabled')?'':(localStorage.getItem('upright_token')||localStorage.getItem('alldogs_token')||'').trim();}catch{return '';}}
function status(s){$('#save-status').textContent=s;$('#review-save').textContent=s;}
function persist(){revision++;try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}status(storageOK?'Saved in this browser'+(connected?' · syncing…':'. Connect to save on your server.'):'Browser storage unavailable. Export your notes before closing.');if(connected)queueSync();}
let syncTimer;
function queueSync(){clearTimeout(syncTimer);syncTimer=setTimeout(sync,600);}
async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{'Authorization':'Bearer '+key(),'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(r.status===403?'Review key was not accepted.':r.status===409?'Feedback changed in another browser. Please retry.':'Feedback service unavailable.');return r.json();}
function merge(remote){for(const area of ['reviews','pairs','attributes'])for(const [id,v] of Object.entries(remote[area]||{})){if(!state[area][id]||(v.updatedAt||0)>(state[area][id].updatedAt||0))state[area][id]=v;}if((remote.recipe?.updatedAt||0)>(state.recipe.updatedAt||0))state.recipe=remote.recipe;}
async function sync(){if(!connected)return;if(syncing){resync=true;return;}syncing=true;const sentRevision=revision;try{const result=await request('/feedback',{method:'POST',body:JSON.stringify(state)});merge(result);try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;}if(sentRevision===revision)status('Saved privately on your art server.');else resync=true;renderWall();renderWords();renderRound();if(current&&document.activeElement!==$('#review-note'))renderReview();return true;}catch(e){status((storageOK?'Saved in this browser. ':'Not saved locally. ')+e.message+' Retry with Connect feedback.');return false;}finally{syncing=false;if(resync){resync=false;queueSync();}}}
async function connect(){const remote=await request('/feedback');merge(remote);connected=true;$('#connect').textContent='Feedback connected';const saved=await sync();if(saved===false)throw Error('Connected, but upload failed. Your notes remain in this browser.');}
function review(id){return state.reviews[id]||{verdict:'',parts:[],directions:{},note:'',updatedAt:0};}
function updateReview(patch){state.reviews[current]={...review(current),...patch,updatedAt:Date.now()};persist();renderWall();renderRound();}
function switchView(view){$$('.view').forEach(el=>el.hidden=el.id!==view);$$('[data-view]').forEach(el=>el.setAttribute('aria-pressed',el.dataset.view===view));if(view==='round')renderRound();}
const verdicts=[['further','Take this further'],['parts','Keep some parts'],['leave','Leave this direction']];
function renderWall(){const visible=portraits.filter(p=>{if(filter==='All')return true;if(filter==='Reviewed')return !!state.reviews[p.id];if(filter==='Featured')return p.featured;return p.group===filter;});$('#count').textContent=visible.length+' of '+portraits.length+' studies';$('#wall').innerHTML=visible.length?visible.map(p=>`<article class="card"><button class="art-button" data-review="${p.id}" aria-label="Review ${escape(p.title)}"><img src="${p.image}" alt="${escape(p.title)}" width="1000" height="1000" loading="lazy"></button><div class="card-head"><h2>${escape(p.title)}</h2><button class="card-action" data-review="${p.id}">Review ↗</button></div><p class="meta">${escape(p.status)}</p>${review(p.id).verdict?`<p class="reviewed">You: ${escape(verdicts.find(v=>v[0]===review(p.id).verdict)?.[1]||'Reviewed')}</p>`:''}</article>`).join(''):'<p class="empty">No reviews yet. Open a portrait to start.</p>';}
function openReview(id){current=id;renderReview();$('#review').showModal();}
function renderReview(){const p=byId[current],r=review(current);$('#review-title').textContent=p.title;$('#review-status').textContent=p.status;$('#review-description').textContent=p.description;$('#review-image').src=p.image;$('#review-image').alt=p.title;$('#review-link').href=p.image;$('#review-note').value=r.note||'';$('#verdicts').innerHTML=verdicts.map(([id,label])=>`<button data-verdict="${id}" aria-pressed="${r.verdict===id}">${label}</button>`).join('');$('#parts').innerHTML=['Eyes','Mouth','Cheek','Hair','Body / posture','Palette','Paint surface'].map(part=>`<button data-part="${part}" aria-pressed="${r.parts.includes(part)}">${part}</button>`).join('');}

function renderCompare(){for(const side of ['left','right']){const p=byId[$('#'+side+'-select').value];$('#'+side+'-image').src=p.image;$('#'+side+'-image').alt=p.title;$('#'+side+'-link').href=p.image;$('#'+side+'-caption').textContent=p.description;}const pair=state.pairs[$('#left-select').value+'|'+$('#right-select').value];$$('[data-pair]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.pair===pair?.choice));$('#pair-status').textContent=pair?'Your preference is saved.':'';}
function renderWords(){$('#words').innerHTML=vocab.map(([id,title,desc,example,evidence])=>`<article class="word"><h3>${title}</h3><p>${desc}</p><p class="meta">${evidence}</p><button class="example" data-review="${example}">See the passage in ${escape(byId[example].title)} ↗</button><button data-move="${id}" aria-pressed="${state.recipe.moves.includes(id)}">${state.recipe.moves.includes(id)?'Selected for the brief':'Carry this forward'}</button></article>`).join('');}
function briefText(){const chosen=vocab.filter(v=>state.recipe.moves.includes(v[0]));const reviews=Object.entries(state.reviews).filter(([id])=>byId[id]);const lines=['UPRIGHT / NEXT PAINTING','Reference: Bowie · accepted painting','Keep: oversized head, small uneven body, strongly unequal eyes; copper / coral / violet.','Aim: '+(state.recipe.intention||'Let expression emerge through paint; retain ambiguity.'),'', 'SELECTED MOVES',...(chosen.length?chosen.map(v=>v[1]+': '+v[2]):['Choose a few moves from the vocabulary.']),'','YOUR PORTRAIT NOTES'];for(const[id,r]of reviews){const p=byId[id];lines.push(p.title+': '+(verdicts.find(v=>v[0]===r.verdict)?.[1]||'Reviewed'));if(r.parts.length)lines.push('Keep: '+r.parts.join(', '));const axes=Object.entries(r.directions).map(([k,v])=>v+' '+k);if(axes.length)lines.push('Next: '+axes.join('; '));if(r.note)lines.push(r.note);}for(const[id,r]of Object.entries(state.pairs)){const[a,b]=id.split('|');if(byId[a]&&byId[b])lines.push('Compare '+byId[a].title+' / '+byId[b].title+': '+({left:'prefer reference',right:'prefer study',both:'both for different reasons',neither:'neither'}[r.choice]));}lines.push('', 'ATTRIBUTE COMPARISONS', ...summarizeChoices(state.attributes,byId));lines.push('','METHOD','One dedicated artist per drawing. State one question before painting. Keep the exact parent and sources. Review the native preview beside its parent before a full-size render. A useful passage need not be a better whole painting. Make a fresh painted composition; do not paste existing parts.');return lines.join('\n');}
function renderRound(){if(document.activeElement!==$('#intention'))$('#intention').value=state.recipe.intention;$('#chosen-moves').innerHTML=state.recipe.moves.map(id=>`<button data-move="${id}" aria-pressed="true">${escape(vocab.find(v=>v[0]===id)?.[1]||id)} ×</button>`).join('');$('#brief').textContent=briefText();$('#experiments').innerHTML=experiments.map(([title,desc],i)=>`<article class="experiment"><h4>${title}</h4><p>${desc}</p><button data-experiment="${i}">Use this as the starting question</button></article>`).join('');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)switchView(b.dataset.view);if(b.dataset.review)openReview(b.dataset.review);if(b.dataset.filter){filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderWall();}if(b.dataset.verdict){const r=review(current);updateReview({verdict:r.verdict===b.dataset.verdict?'':b.dataset.verdict});renderReview();}if(b.dataset.part){const r=review(current),part=b.dataset.part;updateReview({parts:r.parts.includes(part)?r.parts.filter(p=>p!==part):[...r.parts,part]});renderReview();}if(b.dataset.axis){const d={...review(current).directions};if(d[b.dataset.axis]===b.dataset.value)delete d[b.dataset.axis];else d[b.dataset.axis]=b.dataset.value;updateReview({directions:d});renderReview();}if(b.dataset.move){const id=b.dataset.move,m=state.recipe.moves;state.recipe={...state.recipe,moves:m.includes(id)?m.filter(x=>x!==id):[...m,id],updatedAt:Date.now()};persist();renderWords();renderRound();}if(b.dataset.experiment){const ex=experiments[+b.dataset.experiment];state.recipe={moves:ex[2],intention:ex[1],updatedAt:Date.now()};persist();renderWords();renderRound();}if(b.dataset.pair){const a=$('#left-select').value,c=$('#right-select').value;if(a===c){$('#pair-status').textContent='Choose two different paintings first.';return;}state.pairs[a+'|'+c]={choice:b.dataset.pair,updatedAt:Date.now()};persist();renderCompare();renderRound();}});
$('#review-note').addEventListener('input',e=>updateReview({note:e.target.value.slice(0,4000)}));$('#intention').addEventListener('input',e=>{state.recipe={...state.recipe,intention:e.target.value.slice(0,4000),updatedAt:Date.now()};persist();$('#brief').textContent=briefText();});$('#review-compare').onclick=()=>{const p=byId[current];$('#left-select').value=p.parent||'bowie-4';$('#right-select').value=p.id;$('#review').close();switchView('compare');renderCompare();};$('#review-right').onclick=()=>openReview($('#right-select').value);['left','right'].forEach(s=>$('#'+s+'-select').onchange=renderCompare);$('#swap').onclick=()=>{const a=$('#left-select').value;$('#left-select').value=$('#right-select').value;$('#right-select').value=a;renderCompare();};$('#connect').onclick=()=>{$('#review-key').value=key();$('#connection').showModal();};$('#close-connect').onclick=()=>$('#connection').close();$('#disconnect').onclick=()=>{try{localStorage.removeItem('upright_token');localStorage.setItem('upright_connection_disabled','1');}catch{}connected=false;$('#review-key').value='';$('#connect').textContent='Connect feedback';$('#connect-status').textContent='Disconnected. Local notes are retained.';status('Feedback stays in this browser until connected.');};$('#connect-form').onsubmit=async e=>{e.preventDefault();const value=$('#review-key').value.trim();if(!value)return;try{localStorage.setItem('upright_token',value);localStorage.removeItem('upright_connection_disabled');$('#connect-status').textContent='Connecting…';await connect();$('#connect-status').textContent='Connected. Your notes are saved privately.';$('#connection').close();}catch(err){$('#connect-status').textContent=err.message;}};$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({...state,brief:briefText()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='upright-feedback-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('#copy-brief').onclick=async()=>{try{await navigator.clipboard.writeText(briefText());$('#copy-brief').textContent='Brief copied';}catch{$('#copy-brief').textContent='Select and copy the brief below';}};
try{const response=await fetch('catalog.json');if(!response.ok)throw Error('Catalog unavailable');({portraits}=await response.json());byId=Object.fromEntries(portraits.map(p=>[p.id,p]));$('#filters').innerHTML=['Featured','All','Origins','Bowie','Tiffany','Expression','Brushwork','Family','Reviewed'].map(s=>`<button data-filter="${s}" aria-pressed="${s===filter}">${s}</button>`).join('');const options=portraits.map(p=>`<option value="${p.id}">${escape(p.title)}</option>`).join('');$('#left-select').innerHTML=options;$('#right-select').innerHTML=options;$('#left-select').value='bowie-4';$('#right-select').value='mischief-4';renderWall();renderCompare();renderWords();renderRound();nextChoice();if(!storageOK)status('Browser storage unavailable. Export notes before closing.');if(key())connect().catch(e=>status('Local feedback ready. '+e.message));}catch(e){$('#error').hidden=false;$('#error').textContent='The studio could not load. Please reload. '+e.message;}


function choiceControls(loading){busy=loading;$('#choice-pictures').setAttribute('aria-busy',String(loading));['left','right','tie','neither','skip'].forEach(x=>$('#choice-'+x).disabled=loading);$('#choice-undo').disabled=loading||!lastChoice;}
function choiceCount(){$('#choice-count').textContent=Object.values(state.attributes).filter(x=>!x.undone).length+' choices recorded';}
function loadPortrait(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src;});}
async function showChoice(trial){displayed.add(trial.key);choiceControls(true);$('#choice-message').textContent='Loading pair…';try{await Promise.all([loadPortrait(byId[trial.left].image),loadPortrait(byId[trial.right].image)]);activeTrial=trial;displayed.add(trial.key);$('#choice-left-image').src=byId[trial.left].image;$('#choice-right-image').src=byId[trial.right].image;$('#choice-question').textContent=QUESTIONS.find(q=>q.id===trial.attribute).question;$('#choice-message').textContent='';choiceCount();choiceControls(false);}catch{activeTrial=null;$('#choice-message').textContent='A portrait could not load. Skip to try another pair.';$('#choice-skip').disabled=false;busy=false;}}
async function nextChoice(){const trial=nextTrial(portraits,state.attributes,displayed,previousTrial);if(!trial){choiceControls(true);busy=false;$('#choice-undo').disabled=!lastChoice;$('#choice-question').textContent='You have reviewed every pairing.';$('#choice-message').textContent='Your choices are ready in the next-round brief.';return;}await showChoice(trial);}
function answerChoice(choice){if(busy||!activeTrial||Date.now()<cooldownUntil)return;cooldownUntil=Date.now()+500;const t=activeTrial;lastChoice={...t};state.attributes[t.key]={attribute:t.attribute,left:t.left,right:t.right,choice,undone:false,updatedAt:Date.now()};previousTrial=t;persist();renderRound();nextChoice();}
$('#choice-left').onclick=()=>answerChoice('left');$('#choice-right').onclick=()=>answerChoice('right');$('#choice-tie').onclick=()=>answerChoice('tie');$('#choice-neither').onclick=()=>answerChoice('neither');
$('#choice-skip').onclick=()=>{if(busy)return;previousTrial=activeTrial;nextChoice();};
$('#choice-undo').onclick=()=>{if(busy||!lastChoice)return;const t=lastChoice;state.attributes[t.key]={...state.attributes[t.key],undone:true,updatedAt:Date.now()};lastChoice=null;persist();renderRound();showChoice(t);};
