// ALL DOGS one of ones: the year and the costume, never a name. Generated from the studio roster and the round 1388 painter rows.
window.ALLDOGS_CAP = {
  1: [33, "White robe, red sash, tired kind eyes, a crown of thorns with thin lines of blood, a faint ring of light."],
  2: [1972, "White rhinestone jumpsuit, pompadour, gold aviators, collar to the ears."],
  3: [1978, "White cassock, tall mitre, one paw raised in blessing."],
  4: [1994, "Permed halo, denim shirt, loaded palette, a tiny happy tree."],
  5: [1955, "White fur cape, jewelled toes, a lit candelabra on a piano lid."],
  6: [1977, "Platinum bouffant taller than the skull, an enormous bust in a low-cut rhinestone top, a small guitar, a butterfly."],
  7: [1988, "Feathered headdress bigger than the dog, black hair to the floor."],
  8: [1984, "Purple ruffles, high collar, one lace glove, the unpronounceable guitar."],
  9: [1973, "Red-and-blue bolt across the face, red mullet, a gold circle on the brow."],
  10: [1986, "Yellow military jacket, thick mustache, one fist up, half a mic stand."],
  11: [2004, "Brown, short flat muzzle, the pout and heavy-lidded eyes, shutter shades pushed up on the forehead, varsity jacket, a small brown teddy at the foot."],
  12: [2014, "White bodysuit, long black hair, a phone held out with the dog on the screen."],
  13: [1954, "White halter dress blown straight up, subway grate, a beauty mark."],
  14: [1981, "Razor-flat fade, angular black suit, one huge hoop."],
  15: [1964, "Silver wig, round black glasses, black turtleneck, one soup can, and the 1954 dog as a candy-coloured silkscreen block on the wall."],
  16: [1931, "Waxed mustache past the ears, wild eyes, a clock melting on the shoulder."],
  17: [1997, "Black leather jacket, hair blown back, eyes too open, fire behind."],
  18: [2003, "Dark brown, a bold tribal tattoo around the left eye, red boxing gloves, a pigeon sitting on the head."],
  19: [1982, "Mohawk, gold hoops, a mountain of chains from chin to chest."],
  20: [1974, "Starred white leather, short cape, helmet under one arm, a row of buses."],
  21: [1983, "One sequined glove, tilted fedora, red zipper jacket, up on the toes."],
  22: [2001, "Round glasses, a lightning scar, a striped scarf, an owl on the shoulder."],
  23: [1998, "An enormous dog, a tiny pink umbrella, moleskin and beetle buttons."],
  24: [2007, "Greasy black hair, high black collar, one eyebrow, a small glass vial."],
  25: [1937, "Hairy feet, a waistcoat, a plain gold ring too big for the paw. No writing."],
  26: [2002, "Pointed hat, long grey beard, wooden staff, a firework in the pocket."],
  27: [2013, "Forked beard, a hood, an axe. Short, wide, pleased with itself."],
  28: [1980, "Black mask and cape, a ribbed chest box. No emblem."],
  29: [1999, "Huge ears, small body, a cane, very old eyes."],
  30: [2015, "Three buns, a staff, a round rolling droid at the foot. Desert light."],
  31: [1667, "A red dog, horns, goatee, arrow-tipped tail, goat legs, a pitchfork, small flames at the feet. Delighted."],
  32: [1992, "A ball of a body, red jacket, teal beanie with a yellow pompom, yellow mittens, tiny eyes, a sour mouth. Snow."],
  33: [1993, "Two dogs in one frame on a sagging couch, lit by the TV. Blond pompadour and underbite; peaked hair and braces. No lettering on the shirts."],
  34: [1990, "High platinum ponytail, pink cone-bra corset, headset mic, stage grin."],
  35: [2010, "A dress cut from raw meat, meat hat, meat boots, one eyebrow up."],
  36: [1975, "Sequined baseball uniform, giant rhinestone glasses, a huge grin, a piano lid behind."],
  37: [1987, "Top hat, black curls over the face, round shades, a sunburst guitar slung low, a cigarette."],
  38: [1985, "Yellow bandana, horseshoe mustache, torn yellow tank, red trunks, both arms flexed, orange tan."],
  39: [1979, "Dreadlocks, red-gold-green tam, denim shirt, acoustic guitar, a curl of smoke. Brown coat."],
  40: [1970, "Long black hair, small round purple glasses, a big cross, a bat in the mouth."],
  41: [2018, "Black-rimmed glasses, short beard, hoodie under a workwear vest, a hazard-striped band with nothing on it, one white sneaker held up with an orange zip tag. Brown coat."],
  42: [2000, "Khaki shorts and shirt, a crocodile clamped under one arm, thrilled eyes, huge grin."],
  43: [1968, "Red zip cardigan, blue sneakers, neat grey part, a tiny red trolley at the foot. The kindest face."],
  44: [1956, "Tall glossy pompadour, pencil mustache, sequined jacket, mid-whoop, one leg up on a piano. Brown coat."],
  45: [1967, "Headband, big afro, fringed velvet jacket, kneeling over a burning guitar. Brown coat."],
  46: [2008, "Huge black beehive, winged eyeliner, tattooed arms, a drink, a tiny frame under all that hair."],
  47: [1996, "Red one-piece, huge blonde blowout, a red rescue float, running on sand."],
  48: [2011, "Long brown curls, loud Hawaiian shirt, an accordion mid-squeeze, eyes crossed."],
  49: [1863, "Stovepipe hat, chin beard with no mustache, black coat, bow tie, hollow cheeks, very tall."],
  50: [1776, "Powdered wig with a ribbon, blue coat with gold buttons, in the bow of a rowboat on an icy river."],
  51: [1804, "Sideways bicorne, one paw tucked in the coat, epaulettes, red sash, short."],
  52: [1951, "White hair in every direction, white mustache, cardigan, tongue all the way out."],
  53: [1940, "Bowler, polka-dot bow tie, fat cigar, a V sign, jowls, black overcoat."],
  54: [1930, "Bald, round wire glasses, white shawl and dhoti, sandals, a tall walking staff. Brown coat."],
  55: [1953, "Jewelled crown, pale blue coat, white gloves, black handbag, a corgi at the foot. A dog with a dog."],
  56: [1912, "Pince-nez on a cord, thick mustache, a grin of big square teeth, safari jacket and hat."],
  57: [1961, "Thick side-parted hair, dark sunglasses, navy crewneck, tanned squint, a sailboat behind."],
  58: [1969, "Heavy jowls, widow's peak, dark suit, both arms up in a double V sign."],
  59: [1752, "Bald crown with long grey hair, small bifocals, a kite string with a key tied on, lightning behind."],
  60: [1789, "A wig taller than the dog with a model ship in it, panniered gown, a slice of cake held out."],
  61: [1600, "Stiff white ruff, high bald forehead, goatee, a quill, a skull held up."],
  62: [2012, "Grey-templed crop, big ears, navy suit, red tie, drawn in the flat cream-blue-navy-red poster palette."],
  63: [2016, "Orange coat, blond comb-over, long red tie past the belt, a red cap, pursed mouth, pinching paws."],
  64: [1976, "Grey sweatsuit, black knit cap, red gloves, a glass of raw eggs, running up stone steps at dawn."],
  65: [2006, "Red bandana under a tricorn, beaded braids, kohl eyes, gold tooth, an open compass, swaying."],
  66: [1989, "Brown fedora, leather jacket, coiled whip, satchel, a golden idol held up, a boulder behind."],
  67: [1991, "Two long black braids, black dress with a white collar, dead-level stare, a severed hand at the foot."],
  68: [1995, "Cream suit, blue check shirt, a park bench, a box of chocolates on the knee, a feather."],
  69: [1971, "Purple velvet coat, brown top hat, bow tie, cane, a blank gold ticket, a river of chocolate."],
  70: [1966, "Grey suit, blue cowl with ears, blue cape, yellow belt, a plain yellow oval on the chest. No bat in it."],
  71: [2017, "White face, orange tufts, red nose, ruffled collar, grey Victorian clown suit, a red balloon, too many teeth."],
  72: [1962, "Black tuxedo, bow tie, a martini, one eyebrow up, a gun-barrel spiral behind."],
  73: [1933, "A giant dark ape-shaped dog on top of a skyscraper, biplanes circling, a tiny blonde held gently in one paw."],
  74: [2022, "Leather bomber heavy with patches, aviators, dog tags, a jet tail behind."],
  75: [1928, "Black and white, film grain. A sailor cap, a ship's wheel gripped in both paws, whistled notes. The 1928 public-domain one, on purpose."],
  76: [1935, "Akita upright on a snowy platform under a clock, an empty bench, nobody coming."],
  77: [1957, "A small mongrel strapped in a riveted capsule, the blue curve of the planet below."],
  78: [1872, "A shaggy grey dog flat on a churchyard grave in the rain, a tin bowl."],
  79: [1898, "White terrier, one black ear, head cocked at a brass gramophone horn bigger than he is."],
  80: [79, "Cast in grey ash on its back, a studded collar, a chain to a ring, one red glow."],
  81: [-1178, "An old thin hound on straw in a courtyard, tail lifting for the first time in twenty years, a great bow on the wall."],
  82: [1925, "Lead sled dog leaning into a white-out, a small crate lashed behind. No statue anywhere."],
  83: [2005, "Two identical silk-coated hounds, one drawn fainter, a glass dish and a pipette."],
  84: [1888, "Terrier in a harness of brass tags on a mailbag in a railway-car door."],
  85: [1814, "A St Bernard with a keg on the collar and a child on its back, a blizzard."],
  86: [1918, "Brindle bull terrier in an army coat with stripes and medals, a helmet too big."],
  87: [1944, "A Yorkie inside an upturned steel helmet under a parachute."],
  88: [1942, "A pointer planted barking between ragged men and a raised stick. Brave, never pitiable."],
  89: [1861, "Two fat dogs on a saloon step with a string of sausages. One seed, two dogs."],
  90: [1960, "Two small dogs in orange flight suits on a scorched capsule in a wheat field. One seed, two dogs."],
  91: [1952, "A cocker spaniel at a chrome microphone before a TV camera, entirely innocent."],
  92: [1923, "A burr-covered collie walking a dirt road toward a porch, a trail of prints the length of the picture."],
  93: [1943, "A white shepherd-mix at a dusk bus stop, the bus arriving, fourteen tally strokes on the post."],
  94: [1897, "Laboratory harness, a brass bell, a bowl, one drop at the lip, tallies on a chalkboard."],
  95: [1808, "A Newfoundland on a carved plinth under a poet's cloak, the inscription too worn to read."],
  96: [1929, "A shepherd in a rigid guide harness at a curb, a taxi grille, a white cane laid down."],
  97: [1938, "A mutt in a sailor's cap and peacoat at a ship's rail with a coffee mug, one ear inside out."],
  98: [1900, "A dark terrier in a wicker basket in a gingham lap, a cyclone behind, silver shoes. The book, not the film."],
  99: [1906, "A brown terrier finished in bronze on a drinking fountain over a stick-figure crowd with raised sticks."],
  100: [1921, "A collie content on a lab bench, a syringe on a tray, seventy days struck through on a calendar."],
  101: [1889, "Red beard, straw hat, blue smock, a bandage under the hat, sunflowers in both paws, a swirling night behind."],
  102: [1939, "One brow across both eyes, braids, a flower crown, an embroidered dress, a monkey on the shoulder, a parrot."],
  103: [1907, "Bald dome, striped sailor shirt, huge dark eyes, one eye in profile on a frontal face, a cigarette."],
  104: [1965, "Red bob wig, a red dress in white dots, dots on the coat and the ground, a dotted pumpkin."],
  105: [1831, "An old dog in a blue kimono with a brush, a great clawed wave over everything, a small white mountain."],
  106: [1503, "Long white hair and beard, a red cap, a rose robe, paws folded, the faintest smile, a misty river."],
  107: [1950, "Black t-shirt, jeans, a cigarette, a paint can pouring from one paw, drips across everything."],
  108: [1899, "Long white beard, straw hat, a palette, on a green bridge over lily pads."],
  109: [2007, "Black turtleneck, jeans, rimless glasses, stubble, a blank white rectangle held up."],
  110: [2020, "Black t-shirt, a rocket on a barge behind, a tiny red car, a manic grin, a finger at the sky."],
  111: [1998, "Red jersey, bald, one gold hoop, tongue out, a ball palmed in mid-air, a hoop behind."],
  112: [2006, "Purple and gold, a headband, leaning back into a fadeaway."],
  113: [1958, "A young dog in a yellow shirt and blue shorts, upside down in a bicycle kick."],
  114: [2021, "Sky-blue stripes, a short beard, a gold cup held up in confetti."],
  115: [2019, "Red polo, a blank black cap, a fist pumped, a club in the other paw, a green with a flag."],
  116: [2024, "A high ponytail, black and gold, a ball just leaving the paws from the centre line, three fingers up."],
  117: [1985, "Two parallel fire trails burning across the road behind him; the red puffer vest over a denim jacket."],
  118: [1961, "The black sheath and the pearls, the dark glasses, the tall updo with a small tiara, the long cigarette holder."],
  119: [1973, "The yellow suit with one black stripe running the length of the body and down every leg; the black bowl cut."],
  120: [1977, "The white three-piece over a black shirt; one forepaw pointing straight up."],
  121: [1980, "The split door plane behind, a hole around the head; the axe at the paws."],
  122: [1994, "The thin black tie; two fingers across the eyes; a black suit."],
  123: [1939, "The red sequin shoes; a blue checked pinafore; a basket at the paws with a small blob in it."],
  124: [1942, "A belted khaki trench, a dark fedora, one airfield lamp burning in the fog."],
  125: [1959, "A grey suit in a dry empty field, one small plane low on the closed side."],
  126: [1960, "A hanging pale curtain, a raised knife as a dark ribbon on it, one wide eye."],
  127: [1968, "A tall black slab standing in red rock, a bone held in the mouth."],
  128: [1975, "One dark fin cutting the night water; a small yellow barrel at the forepaws."],
  129: [1977, "Two round side buns of dark hair on a tight cap; a white hooded gown; a blue disc at the paws."],
  130: [1979, "A white table in a white ship room; a small pale creature standing on it."],
  131: [1982, "A glowing fingertip from off-frame meeting the raised paw; a red hoodie; one moon."],
  132: [1984, "The black leather jacket, the black glasses, a small red glint in one lens."],
  133: [1986, "Aviators, dog tags, jeans, no shirt, a volleyball at the paws."],
  134: [1989, "The trench coat, a boombox held up in both forepaws."],
  135: [1987, "The pink dress, arms out, body straight, lifted."],
  136: [1988, "A white vest gone grey, bare paws, a box at the mouth."],
  137: [1989, "A sandwich at the paws, one pale table, the head thrown back."],
  138: [1990, "Clay-grey forepaws on a wheel, a white shirt."],
  139: [1991, "A white jumpsuit, a dead-level stare, one glass plane with a dark bar."],
  140: [1993, "The red flare in the mouth, a spray at the burning tip."],
  141: [1994, "The red cap and the long beard on a white shirt."],
};
