// ALL DOGS one of ones: [year, costume, first name]. First names or one-word names only, never a full name (Jon, 2026-09-04; site only, reversible).
window.ALLDOGS_CAP = {
  1: [33, "White robe, red sash, tired kind eyes, a crown of thorns with thin lines of blood, a faint ring of light.", "Jesus"],
  2: [1972, "White rhinestone jumpsuit, pompadour, gold aviators, collar to the ears.", "Elvis"],
  3: [1978, "White cassock, tall mitre, one paw raised in blessing.", "John Paul"],
  4: [1994, "Permed halo, denim shirt, loaded palette, a tiny happy tree.", "Bob"],
  5: [1955, "White fur cape, jewelled toes, a lit candelabra on a piano lid.", "Liberace"],
  6: [1977, "Platinum bouffant taller than the skull, an enormous bust in a low-cut rhinestone top, a small guitar, a butterfly.", "Dolly"],
  7: [1988, "Feathered headdress bigger than the dog, black hair to the floor.", "Cher"],
  8: [1984, "Purple ruffles, high collar, one lace glove, the unpronounceable guitar.", "Prince"],
  9: [1973, "Red-and-blue bolt across the face, red mullet, a gold circle on the brow.", "Ziggy"],
  10: [1986, "Yellow military jacket, thick mustache, one fist up, half a mic stand.", "Freddie"],
  11: [2004, "Brown, short flat muzzle, the pout and heavy-lidded eyes, shutter shades pushed up on the forehead, varsity jacket, a small brown teddy at the foot.", "Ye"],
  12: [2014, "White bodysuit, long black hair, a phone held out with the dog on the screen.", "Kim"],
  13: [1954, "White halter dress blown straight up, subway grate, a beauty mark.", "Marilyn"],
  14: [1981, "Razor-flat fade, angular black suit, one huge hoop.", "Grace"],
  15: [1964, "Silver wig, round black glasses, black turtleneck, one soup can, and the 1954 dog as a candy-coloured silkscreen block on the wall.", "Andy"],
  16: [1931, "Waxed mustache past the ears, wild eyes, a clock melting on the shoulder.", "Salvador"],
  17: [1997, "Black leather jacket, hair blown back, eyes too open, fire behind.", "Nicolas"],
  18: [2003, "Dark brown, a bold tribal tattoo around the left eye, red boxing gloves, a pigeon sitting on the head.", "Mike"],
  19: [1982, "Mohawk, gold hoops, a mountain of chains from chin to chest.", "Mr. T"],
  20: [1974, "Starred white leather, short cape, helmet under one arm, a row of buses.", "Evel"],
  21: [1983, "One sequined glove, tilted fedora, red zipper jacket, up on the toes.", "Michael"],
  22: [2001, "Round glasses, a lightning scar, a striped scarf, an owl on the shoulder.", "Harry"],
  23: [1998, "An enormous dog, a tiny pink umbrella, moleskin and beetle buttons.", "Hagrid"],
  24: [2007, "Greasy black hair, high black collar, one eyebrow, a small glass vial.", "Severus"],
  25: [1937, "Hairy feet, a waistcoat, a plain gold ring too big for the paw. No writing.", "Bilbo"],
  26: [2002, "Pointed hat, long grey beard, wooden staff, a firework in the pocket.", "Gandalf"],
  27: [2013, "Forked beard, a hood, an axe. Short, wide, pleased with itself.", "Gimli"],
  28: [1980, "Black mask and cape, a ribbed chest box. No emblem.", "Vader"],
  29: [1999, "Huge ears, small body, a cane, very old eyes.", "Yoda"],
  30: [2015, "Three buns, a staff, a round rolling droid at the foot. Desert light.", "Rey"],
  31: [1667, "A red dog, horns, goatee, arrow-tipped tail, goat legs, a pitchfork, small flames at the feet. Delighted.", "Satan"],
  32: [1992, "A ball of a body, red jacket, teal beanie with a yellow pompom, yellow mittens, tiny eyes, a sour mouth. Snow.", "Cartman"],
  33: [1993, "Two dogs in one frame on a sagging couch, lit by the TV. Blond pompadour and underbite; peaked hair and braces. No lettering on the shirts.", "Beavis & Butt-Head"],
  34: [1990, "High platinum ponytail, pink cone-bra corset, headset mic, stage grin.", "Madonna"],
  35: [2010, "A dress cut from raw meat, meat hat, meat boots, one eyebrow up.", "Gaga"],
  36: [1975, "Sequined baseball uniform, giant rhinestone glasses, a huge grin, a piano lid behind.", "Elton"],
  37: [1987, "Top hat, black curls over the face, round shades, a sunburst guitar slung low, a cigarette.", "Slash"],
  38: [1985, "Yellow bandana, horseshoe mustache, torn yellow tank, red trunks, both arms flexed, orange tan.", "Hulk"],
  39: [1979, "Dreadlocks, red-gold-green tam, denim shirt, acoustic guitar, a curl of smoke. Brown coat.", "Bob"],
  40: [1970, "Long black hair, small round purple glasses, a big cross, a bat in the mouth.", "Ozzy"],
  41: [2018, "Black-rimmed glasses, short beard, hoodie under a workwear vest, a hazard-striped band with nothing on it, one white sneaker held up with an orange zip tag. Brown coat.", "Virgil"],
  42: [2000, "Khaki shorts and shirt, a crocodile clamped under one arm, thrilled eyes, huge grin.", "Steve"],
  43: [1968, "Red zip cardigan, blue sneakers, neat grey part, a tiny red trolley at the foot. The kindest face.", "Fred"],
  44: [1956, "Tall glossy pompadour, pencil mustache, sequined jacket, mid-whoop, one leg up on a piano. Brown coat.", "Little Richard"],
  45: [1967, "Headband, big afro, fringed velvet jacket, kneeling over a burning guitar. Brown coat.", "Jimi"],
  46: [2008, "Huge black beehive, winged eyeliner, tattooed arms, a drink, a tiny frame under all that hair.", "Amy"],
  47: [1996, "Red one-piece, huge blonde blowout, a red rescue float, running on sand.", "Pam"],
  48: [2011, "Long brown curls, loud Hawaiian shirt, an accordion mid-squeeze, eyes crossed.", "Weird Al"],
  49: [1863, "Stovepipe hat, chin beard with no mustache, black coat, bow tie, hollow cheeks, very tall.", "Abe"],
  50: [1776, "Powdered wig with a ribbon, blue coat with gold buttons, in the bow of a rowboat on an icy river.", "George"],
  51: [1804, "Sideways bicorne, one paw tucked in the coat, epaulettes, red sash, short.", "Napoleon"],
  52: [1951, "White hair in every direction, white mustache, cardigan, tongue all the way out.", "Albert"],
  53: [1940, "Bowler, polka-dot bow tie, fat cigar, a V sign, jowls, black overcoat.", "Winston"],
  54: [1930, "Bald, round wire glasses, white shawl and dhoti, sandals, a tall walking staff. Brown coat.", "Gandhi"],
  55: [1953, "Jewelled crown, pale blue coat, white gloves, black handbag, a corgi at the foot. A dog with a dog.", "Elizabeth"],
  56: [1912, "Pince-nez on a cord, thick mustache, a grin of big square teeth, safari jacket and hat.", "Teddy"],
  57: [1961, "Thick side-parted hair, dark sunglasses, navy crewneck, tanned squint, a sailboat behind.", "Jack"],
  58: [1969, "Heavy jowls, widow's peak, dark suit, both arms up in a double V sign.", "Richard"],
  59: [1752, "Bald crown with long grey hair, small bifocals, a kite string with a key tied on, lightning behind.", "Ben"],
  60: [1789, "A wig taller than the dog with a model ship in it, panniered gown, a slice of cake held out.", "Marie"],
  61: [1600, "Stiff white ruff, high bald forehead, goatee, a quill, a skull held up.", "William"],
  62: [2012, "Grey-templed crop, big ears, navy suit, red tie, drawn in the flat cream-blue-navy-red poster palette.", "Barack"],
  63: [2016, "Orange coat, blond comb-over, long red tie past the belt, a red cap, pursed mouth, pinching paws.", "Donald"],
  64: [1976, "Grey sweatsuit, black knit cap, red gloves, a glass of raw eggs, running up stone steps at dawn.", "Rocky"],
  65: [2006, "Red bandana under a tricorn, beaded braids, kohl eyes, gold tooth, an open compass, swaying.", "Jack"],
  66: [1989, "Brown fedora, leather jacket, coiled whip, satchel, a golden idol held up, a boulder behind.", "Indy"],
  67: [1991, "Two long black braids, black dress with a white collar, dead-level stare, a severed hand at the foot.", "Wednesday"],
  68: [1995, "Cream suit, blue check shirt, a park bench, a box of chocolates on the knee, a feather.", "Forrest"],
  69: [1971, "Purple velvet coat, brown top hat, bow tie, cane, a blank gold ticket, a river of chocolate.", "Willy"],
  70: [1966, "Grey suit, blue cowl with ears, blue cape, yellow belt, a plain yellow oval on the chest. No bat in it.", "Batman"],
  71: [2017, "White face, orange tufts, red nose, ruffled collar, grey Victorian clown suit, a red balloon, too many teeth.", "Pennywise"],
  72: [1962, "Black tuxedo, bow tie, a martini, one eyebrow up, a gun-barrel spiral behind.", "James"],
  73: [1933, "A giant dark ape-shaped dog on top of a skyscraper, biplanes circling, a tiny blonde held gently in one paw.", "Kong"],
  74: [2022, "Leather bomber heavy with patches, aviators, dog tags, a jet tail behind.", "Maverick"],
  75: [1928, "Black and white, film grain. A sailor cap, a ship's wheel gripped in both paws, whistled notes. The 1928 public-domain one, on purpose.", "Willie"],
  76: [1935, "Akita upright on a snowy platform under a clock, an empty bench, nobody coming.", "Hachiko"],
  77: [1957, "A small mongrel strapped in a riveted capsule, the blue curve of the planet below.", "Laika"],
  78: [1872, "A shaggy grey dog flat on a churchyard grave in the rain, a tin bowl.", "Bobby"],
  79: [1898, "White terrier, one black ear, head cocked at a brass gramophone horn bigger than he is.", "Nipper"],
  80: [79, "Cast in grey ash on its back, a studded collar, a chain to a ring, one red glow.", "Pompeii"],
  81: [-1178, "An old thin hound on straw in a courtyard, tail lifting for the first time in twenty years, a great bow on the wall.", "Argos"],
  82: [1925, "Lead sled dog leaning into a white-out, a small crate lashed behind. No statue anywhere.", "Togo"],
  83: [2005, "Two identical silk-coated hounds, one drawn fainter, a glass dish and a pipette.", "Snuppy"],
  84: [1888, "Terrier in a harness of brass tags on a mailbag in a railway-car door.", "Owney"],
  85: [1814, "A St Bernard with a keg on the collar and a child on its back, a blizzard.", "Barry"],
  86: [1918, "Brindle bull terrier in an army coat with stripes and medals, a helmet too big.", "Stubby"],
  87: [1944, "A Yorkie inside an upturned steel helmet under a parachute.", "Smoky"],
  88: [1942, "A pointer planted barking between ragged men and a raised stick. Brave, never pitiable.", "Judy"],
  89: [1861, "Two fat dogs on a saloon step with a string of sausages. One seed, two dogs.", "Bummer & Lazarus"],
  90: [1960, "Two small dogs in orange flight suits on a scorched capsule in a wheat field. One seed, two dogs.", "Belka & Strelka"],
  91: [1952, "A cocker spaniel at a chrome microphone before a TV camera, entirely innocent.", "Checkers"],
  92: [1923, "A burr-covered collie walking a dirt road toward a porch, a trail of prints the length of the picture.", "Bobbie"],
  93: [1943, "A white shepherd-mix at a dusk bus stop, the bus arriving, fourteen tally strokes on the post.", "Fido"],
  94: [1897, "Laboratory harness, a brass bell, a bowl, one drop at the lip, tallies on a chalkboard.", "Pavlov's dog"],
  95: [1808, "A Newfoundland on a carved plinth under a poet's cloak, the inscription too worn to read.", "Boatswain"],
  96: [1929, "A shepherd in a rigid guide harness at a curb, a taxi grille, a white cane laid down.", "Buddy"],
  97: [1938, "A mutt in a sailor's cap and peacoat at a ship's rail with a coffee mug, one ear inside out.", "Sinbad"],
  98: [1900, "A dark terrier in a wicker basket in a gingham lap, a cyclone behind, silver shoes. The book, not the film.", "Toto"],
  99: [1906, "A brown terrier finished in bronze on a drinking fountain over a stick-figure crowd with raised sticks.", "Brown Dog"],
  100: [1921, "A collie content on a lab bench, a syringe on a tray, seventy days struck through on a calendar.", "Marjorie"],
  101: [1889, "Red beard, straw hat, blue smock, a bandage under the hat, sunflowers in both paws, a swirling night behind.", "Vincent"],
  102: [1939, "One brow across both eyes, braids, a flower crown, an embroidered dress, a monkey on the shoulder, a parrot.", "Frida"],
  103: [1907, "Bald dome, striped sailor shirt, huge dark eyes, one eye in profile on a frontal face, a cigarette.", "Pablo"],
  104: [1965, "Red bob wig, a red dress in white dots, dots on the coat and the ground, a dotted pumpkin.", "Yayoi"],
  105: [1831, "An old dog in a blue kimono with a brush, a great clawed wave over everything, a small white mountain.", "Hokusai"],
  106: [1503, "Long white hair and beard, a red cap, a rose robe, paws folded, the faintest smile, a misty river.", "Leonardo"],
  107: [1950, "Black t-shirt, jeans, a cigarette, a paint can pouring from one paw, drips across everything.", "Jackson"],
  108: [1899, "Long white beard, straw hat, a palette, on a green bridge over lily pads.", "Claude"],
  109: [2007, "Black turtleneck, jeans, rimless glasses, stubble, a blank white rectangle held up.", "Steve"],
  110: [2020, "Black t-shirt, a rocket on a barge behind, a tiny red car, a manic grin, a finger at the sky.", "Elon"],
  111: [1998, "Red jersey, bald, one gold hoop, tongue out, a ball palmed in mid-air, a hoop behind.", "MJ"],
  112: [2006, "Purple and gold, a headband, leaning back into a fadeaway.", "Kobe"],
  113: [1958, "A young dog in a yellow shirt and blue shorts, upside down in a bicycle kick.", "Pele"],
  114: [2021, "Sky-blue stripes, a short beard, a gold cup held up in confetti.", "Leo"],
  115: [2019, "Red polo, a blank black cap, a fist pumped, a club in the other paw, a green with a flag.", "Tiger"],
  116: [2024, "A high ponytail, black and gold, a ball just leaving the paws from the centre line, three fingers up.", "Caitlin"],
  117: [1985, "Two parallel fire trails burning across the road behind him; the red puffer vest over a denim jacket.", "Marty"],
  118: [1961, "The black sheath and the pearls, the dark glasses, the tall updo with a small tiara, the long cigarette holder.", "Holly"],
  119: [1973, "The yellow suit with one black stripe running the length of the body and down every leg; the black bowl cut.", "Bruce"],
  120: [1977, "The white three-piece over a black shirt; one forepaw pointing straight up.", "Tony"],
  121: [1980, "The split door plane behind, a hole around the head; the axe at the paws.", "Jack"],
  122: [1994, "The thin black tie; two fingers across the eyes; a black suit.", "Mia"],
  123: [1939, "The red sequin shoes; a blue checked pinafore; a basket at the paws with a small blob in it.", "Dorothy"],
  124: [1942, "A belted khaki trench, a dark fedora, one airfield lamp burning in the fog.", "Rick"],
  125: [1959, "A grey suit in a dry empty field, one small plane low on the closed side.", "Roger"],
  126: [1960, "A hanging pale curtain, a raised knife as a dark ribbon on it, one wide eye.", "Marion"],
  127: [1968, "A tall black slab standing in red rock, a bone held in the mouth.", "Dave"],
  128: [1975, "One dark fin cutting the night water; a small yellow barrel at the forepaws.", "Jaws"],
  129: [1977, "Two round side buns of dark hair on a tight cap; a white hooded gown; a blue disc at the paws.", "Leia"],
  130: [1979, "A white table in a white ship room; a small pale creature standing on it.", "Kane"],
  131: [1982, "A glowing fingertip from off-frame meeting the raised paw; a red hoodie; one moon.", "Elliott"],
  132: [1984, "The black leather jacket, the black glasses, a small red glint in one lens.", "Arnold"],
  133: [1986, "Aviators, dog tags, jeans, no shirt, a volleyball at the paws.", "Goose"],
  134: [1989, "The trench coat, a boombox held up in both forepaws.", "Lloyd"],
  135: [1987, "The pink dress, arms out, body straight, lifted.", "Baby"],
  136: [1988, "A white vest gone grey, bare paws, a box at the mouth.", "John"],
  137: [1989, "A sandwich at the paws, one pale table, the head thrown back.", "Sally"],
  138: [1990, "Clay-grey forepaws on a wheel, a white shirt.", "Molly"],
  139: [1991, "A white jumpsuit, a dead-level stare, one glass plane with a dark bar.", "Hannibal"],
  140: [1993, "The red flare in the mouth, a spray at the burning tip.", "Alan"],
  141: [1994, "The red cap and the long beard on a white shirt.", "Gump"],
};
