import {slot,emptyState,current,edit,mergeRecords,batch,acknowledge,conflicts,resolve} from './state.js';
const $=s=>document.querySelector(s),API='https://api.alldogs.wtf/collection-api',KEY='all-dogs-loop-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=emptyState(),catalog,byId={},dogs=[],selected,writer=false,connected=false,syncing=false,ready=false,ticket=0,timer,storage=true,summary=null,viewBase=0;
const token=()=>localStorage.getItem('loop_disconnected')?'':(localStorage.getItem('collection_token')||localStorage.getItem('upright_token')||localStorage.getItem('alldogs_token')||'').trim();
function readLocal(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.version===2&&s.records&&s.drafts&&Array.isArray(s.outbox))state=s;}catch{storage=false;}}
readLocal();
function status(s){$('#save-status').textContent=!writer?'Another Loop tab is editing. Close it to edit here; browsing is available.':s;}
function save(){if(!writer)return;try{localStorage.setItem(KEY,JSON.stringify(state));storage=true;}catch{storage=false;status('Browser storage is full or unavailable. Connect and sync, or export before closing.');}renderConflicts();}
function review(id){return current(state,'loopReviews',id)||{score:null,note:'',imageHash:byId[id].imageHash};}
function changed(){save();if(storage)status(connected?'Saved here. Syncing privately…':'Saved in this browser. Connect feedback for private backup across devices.');clearTimeout(timer);if(connected)timer=setTimeout(sync,500);renderArchive();}
function putReview(patch){if(!writer||!ready||!selected)return;const key=slot('loopReviews',selected),had=!!state.drafts[key];edit(state,'loopReviews',selected,{...review(selected),...patch});if(!had)state.drafts[key].baseSeq=viewBase;changed();renderScore();}
async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json'},signal:AbortSignal.timeout(20000)});const data=await r.json();if(r.status===409)return {conflict:data};if(!r.ok)throw Error(r.status===403?'Your review key was not accepted.':'Feedback service unavailable; your unsent notes stay here.');return data;}
async function pull(){let until=null,more=true;while(more){const r=await request('/changes?after='+state.cursor+(until===null?'':'&until='+until));mergeRecords(state,r.records);state.cursor=r.cursor;until=r.until;more=r.more;save();}}
async function sync(){if(!writer||!connected||syncing)return;syncing=true;try{if(!state.outbox.length)await pull();for(let i=0;i<30;i++){const events=batch(state);if(!events.length)break;save();const r=await request('/events',{method:'POST',body:JSON.stringify({events})});if(r.conflict){conflicts(state,r.conflict.conflicts);save();break;}acknowledge(state,r.receipts);for(const x of r.receipts)if(x.area==='loopReviews'&&x.id===selected)viewBase=x.seq;save();}await pull();summary=await request('/loop-summary');renderStats();renderArchive();renderMessages();renderConflicts();if(selected&&document.activeElement!==$('#note'))renderScore(true);status(Object.values(state.drafts).some(d=>d.conflict)?'Two versions need your choice below.':Object.keys(state.drafts).length?'Unsent changes remain here.':'Saved privately. Up to date.');}catch(e){status(e.message);}finally{syncing=false;}}
function renderStats(){if(!summary)return;const n=x=>x===null?'—':x.toFixed(1);$('#baseline').textContent=n(summary.baseline.mean);$('#baseline-count').textContent=summary.baseline.complete?'First 10 · fixed':summary.baseline.count+'/10 scores so far';$('#recent').textContent=n(summary.recent.mean);$('#recent-count').textContent=summary.recent.count+' rated designs';$('#average').textContent=n(summary.currentMean);$('#rated-count').textContent=summary.ratedCount+' rated · '+summary.unratedCount+' unrated';$('#comparison').textContent=summary.overlapCount?'Starting and recent groups share '+summary.overlapCount+' dogs. Improvement is not yet an independent comparison.':summary.baseline.complete&&summary.recent.count===10?('Recent average is '+Math.abs(summary.recent.mean-summary.baseline.mean).toFixed(1)+(summary.recent.mean>=summary.baseline.mean?' above':' below')+' the starting average. Only rated dogs are included.'):'Your first ten scores establish the starting average.';}
function renderScore(note=false){if(!selected)return;const v=review(selected);document.querySelectorAll('[data-score]').forEach(b=>{b.setAttribute('aria-pressed',Number(b.dataset.score)===v.score);b.disabled=!writer||!ready;});$('#note').readOnly=!writer||!ready;$('#save-next').disabled=!writer||!ready;$('#clear-score').disabled=!writer||!ready||v.score===null;if(note){$('#note').value=v.note;viewBase=state.drafts[slot('loopReviews',selected)]?.baseSeq??state.records[slot('loopReviews',selected)]?.seq??0;}}
async function show(id){const d=byId[id];if(!d)return;selected=id;ready=false;const t=++ticket;$('#dog-image').style.visibility='hidden';$('#expand-image').disabled=true;$('#inspect-image').disabled=true;$('#image-resolution').textContent='';$('#dog-title').textContent=d.title;$('#dog-story').textContent=d.description;$('#position').textContent=(dogs.findIndex(x=>x.id===id)+1)+' / '+dogs.length;renderScore(true);history.replaceState(null,'','#dog='+encodeURIComponent(id));try{const im=new Image();im.src=d.image;await im.decode();if(t!==ticket)return;$('#dog-image').src=d.image;$('#dog-image').alt=d.title;$('#full-image').href=d.image;$('#image-resolution').textContent=im.naturalWidth+' × '+im.naturalHeight+' original';$('#dog-image').width=im.naturalWidth;$('#dog-image').height=im.naturalHeight;$('#expand-image').disabled=false;$('#inspect-image').disabled=false;$('#dog-image').style.visibility='visible';ready=true;renderScore();}catch{if(t===ticket)status('This painting could not load. Try the next dog or reload.');}}
let viewerZoom='fit';
function sizeViewer(mode=viewerZoom){viewerZoom=mode;const im=$('#viewer-image'),box=$('#viewer-scroll');if(!im.naturalWidth)return;const style=getComputedStyle(box),w=box.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),h=box.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom);const scale=mode==='fit'?Math.min(1,w/im.naturalWidth,h/im.naturalHeight):Number(mode);im.style.width=Math.round(im.naturalWidth*scale)+'px';im.style.height=Math.round(im.naturalHeight*scale)+'px';document.querySelectorAll('[data-zoom]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.zoom===mode));}
function expandPainting(){if(!ready)return;const im=$('#viewer-image');im.src=$('#dog-image').src;im.alt=$('#dog-image').alt;$('#viewer-title').textContent=byId[selected].title;$('#image-viewer').showModal();viewerZoom='fit';if(im.complete)sizeViewer();im.onload=()=>sizeViewer();$('#viewer-scroll').scrollTo(0,0);}
$('#expand-image').onclick=expandPainting;$('#inspect-image').onclick=expandPainting;
document.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>sizeViewer(b.dataset.zoom));
window.addEventListener('resize',()=>{if($('#image-viewer').open)sizeViewer();});
function changeView(name){document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==name);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===name));if(name==='archive')renderArchive();}
function next(unrated=false,delta=1){if(!dogs.length)return;const start=dogs.findIndex(x=>x.id===selected);for(let n=1;n<=dogs.length;n++){const d=dogs[(start+delta*n+dogs.length*2)%dogs.length];if(!unrated||review(d.id).score===null){show(d.id);return;}}status('You have scored every current dog. New paintings will appear here.');}
function renderArchive(){if(!catalog)return;const filter=$('#filter').value;const list=dogs.filter(d=>filter==='all'||(filter==='rated'?review(d.id).score!==null:review(d.id).score===null));$('#archive-grid').innerHTML=list.map(d=>`<button class="card" data-dog="${esc(d.id)}"><img src="${esc(d.image)}" alt="${esc(d.title)}" loading="lazy" width="1000" height="1000"><div class="caption"><span>${esc(d.title)}</span><span>${review(d.id).score===null?'Unrated':review(d.id).score+' / 10'}</span></div></button>`).join('')||'<p>No dogs in this view yet.</p>';}
function renderMessages(){const messages=new Map;for(const r of Object.values(state.records))if(r.area==='loopFeedback')messages.set(r.id,r);for(const r of Object.values(state.drafts))if(r.area==='loopFeedback')messages.set(r.id,r);$('#messages').innerHTML=[...messages.values()].reverse().map(r=>`<article><small>${r.seq?'Saved feedback':'Waiting to sync'}</small><p>${esc(r.value.note)}</p></article>`).join('');}
function renderConflicts(){const rows=Object.entries(state.drafts).filter(([,d])=>d.conflict);$('#conflicts').hidden=!rows.length;$('#conflicts').innerHTML=rows.map(([key,d])=>`<article><b>Two versions of ${esc(byId[d.id]?.title||'your note')}</b><p>Your unsent version is preserved. Choose which to save.</p><pre>Your version: ${esc(JSON.stringify(d.value))}\nSaved version: ${esc(JSON.stringify(state.records[key]?.value))}</pre><button data-resolve="mine" data-key="${esc(key)}">Keep my version</button> <button data-resolve="saved" data-key="${esc(key)}">Use saved version</button></article>`).join('');}
async function connect(){await request('/changes?after=0&limit=1');connected=true;$('#connect').textContent='Feedback connected';await sync();}
$('#scores').innerHTML=Array.from({length:10},(_,i)=>`<button type="button" data-score="${i+1}" aria-pressed="false" aria-label="Score ${i+1} out of 10" disabled>${i+1}</button>`).join('');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)changeView(b.dataset.view);if(b.dataset.dog){show(b.dataset.dog);changeView('paint');window.scrollTo(0,0);}if(b.dataset.score)putReview({score:Number(b.dataset.score)});if(b.dataset.close)$('#'+b.dataset.close).close();if(b.dataset.resolve&&writer){resolve(state,b.dataset.key,b.dataset.resolve==='mine');changed();renderScore(true);}});
$('#note').oninput=()=>putReview({note:$('#note').value});$('#clear-score').onclick=()=>putReview({score:null});$('#next').onclick=()=>next();$('#previous').onclick=()=>next(false,-1);$('#save-next').onclick=()=>{if(!ready||!writer)return;putReview({note:$('#note').value});next(true);};$('#filter').onchange=renderArchive;
$('#connect').onclick=()=>$('#connection').showModal();$('#connect-form').onsubmit=async e=>{e.preventDefault();if(!writer)return;try{const key=$('#review-key').value.trim();if(!key)return;localStorage.setItem('collection_token',key);localStorage.removeItem('loop_disconnected');await connect();$('#review-key').value='';$('#connection').close();}catch(e){connected=false;$('#connect-status').textContent=e.message;}};$('#sync-now').onclick=()=>{if(connected)sync();else $('#connect-status').textContent='Enter your review key first.';};$('#disconnect').onclick=()=>{connected=false;localStorage.setItem('loop_disconnected','1');$('#connect').textContent='Connect feedback';$('#connection').close();status('Disconnected. Saved drafts remain in this browser.');};
$('#open-feedback').onclick=()=>{renderMessages();$('#feedback').showModal();};$('#feedback-form').onsubmit=e=>{e.preventDefault();if(!writer)return;const note=$('#general-note').value.trim();if(!note)return;edit(state,'loopFeedback',crypto.randomUUID(),{note});changed();renderMessages();$('#general-note').value='';};
$('#export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),feedback:state,summary},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='all-dogs-loop-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
window.addEventListener('focus',()=>{if(connected)sync();});window.addEventListener('online',()=>{if(connected)sync();});window.addEventListener('storage',e=>{if(e.key!==KEY||writer)return;readLocal();renderArchive();renderMessages();renderScore(true);});
try{const r=await fetch('catalog.json',{cache:'no-cache'});if(!r.ok)throw Error('The studio catalogue could not load.');catalog=await r.json();byId=Object.fromEntries(catalog.dogs.map(d=>[d.id,d]));const refIds=new Set(catalog.references.map(x=>x.id));dogs=catalog.dogs.filter(d=>d.kind==='candidate'&&!refIds.has(d.id)).reverse();$('#total').textContent=dogs.length;$('#reference-grid').innerHTML=catalog.references.map(d=>`<a class="card" href="${esc(d.image)}" target="_blank" rel="noopener"><img src="${esc(d.image)}" alt="${esc(d.title)}" width="1000" height="1000" loading="lazy"><div class="caption"><span>${esc(d.title)}</span><span>Permanent reference</span></div></a>`).join('');renderArchive();const id=decodeURIComponent(location.hash.replace(/^#dog=/,''));if(dogs.length)show(dogs.some(d=>d.id===id)?id:dogs[0].id);if(navigator.locks){navigator.locks.request('all-dogs-loop-editor',async()=>{readLocal();writer=true;renderScore(true);renderArchive();$('#general-note').readOnly=false;status('Ready. Your scores guide the next paintings.');if(token())try{await connect();}catch(e){status(e.message);}await new Promise(()=>{});});}else{status('Open in a current browser to edit and safely sync feedback.');$('#general-note').readOnly=true;}}catch(e){$('#error').hidden=false;$('#error').textContent=e.message;}
