import {slot,emptyState,current,edit,mergeRecords,batch,acknowledge,conflicts,resolve,nextTrial} from './state.js?v=collection-1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const API='https://api.alldogs.wtf/collection-api',KEY='alldogs-collection-feedback-v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={love:'Love',keep:'Keep',revise:'Revise',reject:'Reject'};
const parts=['Eyes','Expression','Body / pose','Coat','Clothing','Linework','Paint surface','Palette','Prop','Action marks','Background'];
let state=emptyState(),storage=true,catalog,byId={},trials=[],selected=null,limit=36,connected=false,syncing=false,timer,active=null,previous=null,last=null,busy=false,loadTicket=0;
let noteBaseSeq=0,recipeBaseSeq=0,writer=false,pairReady=false,voteAfter=0;
const skipped=new Set();
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved?.version===2&&saved.records&&saved.drafts&&Array.isArray(saved.outbox))state=saved;}catch{storage=false;}
last=state.lastChoice||null;
function token(){try{return localStorage.getItem('collection_disconnected')?'':(localStorage.getItem('collection_token')||localStorage.getItem('upright_token')||localStorage.getItem('alldogs_token')||'').trim();}catch{return '';}}
function message(text){if(!writer)text='Another collection tab is open. Close it to edit here; you can still browse and export.';$('#save-status').textContent=text;$('#review-save').textContent=text;}
function save(){if(!writer)return;try{localStorage.setItem(KEY,JSON.stringify(state));storage=true;}catch{storage=false;}renderConflicts();}
function pending(){return Object.values(state.drafts).filter(d=>!d.conflict).length;}
function changed(){save();message(storage?(connected?'Saved here · syncing privately…':'Saved in this browser. Connect feedback to save privately on your server.'):'Browser storage is unavailable. Connect or export your notes before closing.');clearTimeout(timer);if(connected)timer=setTimeout(()=>sync().catch(()=>{}),600);}
function value(area,id){return current(state,area,id);}
function review(id){return value('reviews',id)||{verdict:'',parts:[],note:'',imageHash:byId[id].imageHash};}
function put(area,id,v){if(!writer)return false;edit(state,area,id,v);changed();}
async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{'Authorization':'Bearer '+token(),'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(15000)});let data;try{data=await r.json();}catch{throw Error('Feedback service did not respond. Your unsent notes remain here.');}if(r.status===409)return {conflict:data};if(!r.ok){const error=Error(r.status===403?'Review key was not accepted.':(data.error||'Feedback service unavailable.'));error.status=r.status;throw error;}return data;}
async function pull(){let until=null,more=true;while(more){const r=await request('/changes?after='+state.cursor+(until===null?'':'&until='+until));mergeRecords(state,r.records);state.cursor=r.cursor;until=r.until;more=r.more;save();}}
async function sync(){if(!writer||!connected||syncing)return;syncing=true;let failed=false;try{
  if(!state.outbox.length)await pull();
  for(let turn=0;turn<30&&(state.outbox.length||pending());turn++){
    const events=batch(state);save();if(!events.length)break;
    const r=await request('/events',{method:'POST',body:JSON.stringify({events})});
    if(r.conflict){conflicts(state,r.conflict.conflicts);save();continue;}
    acknowledge(state,r.receipts);for(const receipt of r.receipts){if(receipt.area==='reviews'&&receipt.id===selected)noteBaseSeq=receipt.seq;if(receipt.area==='recipe')recipeBaseSeq=receipt.seq;}save();
  }
  await pull();renderWall();renderBrief();renderVocabulary();if(selected&&$('#review').open&&document.activeElement!==$('#review-note'))openReview(selected);renderConflicts();updateChoiceCount();
  const unresolved=Object.values(state.drafts).filter(d=>d.conflict).length;
  message(unresolved?'A note changed in another browser. Choose which version to keep below.':pending()?'Saved here · changes still waiting to sync.':'Saved privately on your art server.');
}catch(e){failed=true;if([400,413,415].includes(e.status)){for(const item of state.outbox){const d=state.drafts[slot(item.event.area,item.event.id)];if(d){d.conflict=true;d.problem='This change could not be validated. Your version is preserved.';}}state.outbox=[];save();}message((storage?'Saved in this browser. ':'')+e.message+' Use Connect feedback to retry.');throw e;}finally{syncing=false;if(!failed&&connected&&(pending()||state.outbox.length))timer=setTimeout(()=>sync().catch(()=>{}),600);}}
async function connect(){await request('/changes?after=0&limit=1');connected=true;$('#connect').textContent='Feedback settings';await sync();}
function changeView(id){$$('.view').forEach(x=>x.hidden=x.id!==id);$$('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.view===id)));if(id==='choices-view'&&!active)showNext();if(id==='brief-view')renderBrief();}
function filtered(){const kind=$('#kind').value,decision=$('#decision').value,q=$('#search').value.toLowerCase().trim();return catalog.dogs.filter(d=>(kind==='all'||(kind==='references'?d.selectedReference:d.kind===kind))&&(decision==='all'||(decision==='unreviewed'?!review(d.id).verdict:review(d.id).verdict===decision))&&(!q||[d.title,d.number,d.description,JSON.stringify(d.traitNotes||''),d.prop].join(' ').toLowerCase().includes(q)));}
function verdictButtons(d){const r=review(d.id);return Object.entries(labels).map(([id,label])=>`<button data-verdict="${id}" data-dog="${d.id}" aria-pressed="${r.verdict===id}" ${!writer?'disabled':''}>${label}</button>`).join('');}
function renderWall(){if(!catalog)return;const all=filtered(),show=all.slice(0,limit),originals=catalog.dogs.filter(d=>d.kind==='original');const kept=originals.filter(d=>['love','keep'].includes(review(d.id).verdict)).length;
 $('#count').textContent=`${all.length} drawings · ${kept} of ${originals.length} originals marked Love or Keep`;
 $('#wall').innerHTML=show.map(d=>`<article class="card"><button class="art" data-review="${d.id}" aria-label="Review ${esc(d.title)}"><img src="${d.image}" alt="${esc(d.title)}" width="1000" height="1000" loading="lazy"></button><h3>${d.number?'#'+d.number+' · ':''}${esc(d.title)}</h3><div class="buttons">${verdictButtons(d)}</div><button data-review="${d.id}">Parts & notes ↗</button></article>`).join('');$('#more').hidden=show.length>=all.length;
 if(!all.length)$('#wall').innerHTML='<p>No drawings match these filters.</p>';}
function openReview(id){$('#review-note').readOnly=!writer;selected=id;noteBaseSeq=state.drafts[slot('reviews',id)]?.baseSeq??state.records[slot('reviews',id)]?.seq??0;const d=byId[id],r=review(id);$('#review-title').textContent=(d.number?'#'+d.number+' · ':'')+d.title;$('#review-image').src=d.image;$('#review-image').alt=d.title;$('#review-link').href=d.image;$('#detail-link').hidden=!d.detail;if(d.detail)$('#detail-link').href=d.detail;$('#review-description').textContent=d.description;$('#review-kind').textContent=d.kind==='study'?'Prop study. Its decision is separate from the original collection.':'Original dog. Your decision applies to this exact drawing.';$('#verdicts').innerHTML=verdictButtons(d);$('#parts').innerHTML=parts.map(p=>`<button data-part="${p}" aria-pressed="${r.parts.includes(p)}" ${!writer?'disabled':''}>${p}</button>`).join('');$('#review-note').value=r.note;$('#compare-parent').hidden=!d.parent;if(!$('#review').open)$('#review').showModal();}
function updateReview(id,patch){if(!writer)return;put('reviews',id,{...review(id),...patch});renderWall();renderBrief();if(selected===id&&$('#review').open){$('#verdicts').innerHTML=verdictButtons(byId[id]);$('#parts').innerHTML=parts.map(p=>`<button data-part="${p}" aria-pressed="${review(id).parts.includes(p)}" ${!writer?'disabled':''}>${p}</button>`).join('');}}
function updateChoiceCount(){const done=trials.filter(t=>{const v=value('choices',t.id);return v&&!v.undone;}).length;$('#choice-count').textContent=`${done} of ${trials.length} choices`;}
function choiceEnabled(on){['choose-left','choose-right','tie','neither','skip'].forEach(id=>$('#'+id).disabled=!(on&&writer));$('#undo').disabled=!writer||!last||busy;}
async function showNext(forced=null){const t=forced||nextTrial(trials,state,skipped,previous);const ticket=++loadTicket;active=null;pairReady=false;busy=true;choiceEnabled(false);$('#left-image').style.visibility='hidden';$('#right-image').style.visibility='hidden';updateChoiceCount();if(!t){busy=false;$('#question').textContent=skipped.size?'This pass is complete.':'This round is complete.';$('#choice-status').textContent=skipped.size?'You can return to the pairs you skipped.':'Your choices are included in the next-round brief.';$('#resume-skipped').hidden=!skipped.size;$('#undo').disabled=!last;return;}
 $('#resume-skipped').hidden=true;$('#question').textContent=t.question;$('#choice-status').textContent='Loading the two drawings…';
 try{await Promise.all([t.left,t.right].map(id=>new Promise((ok,no)=>{const im=new Image();im.onload=ok;im.onerror=no;im.src=byId[id].image;})));if(ticket!==loadTicket)return;$('#left-image').src=byId[t.left].image;$('#right-image').src=byId[t.right].image;active=t;pairReady=true;$('#left-image').style.visibility='visible';$('#right-image').style.visibility='visible';busy=false;choiceEnabled(true);$('#choice-status').textContent='';}catch{if(ticket!==loadTicket)return;busy=false;active=t;$('#choice-status').textContent='An image could not load. Skip this pair and try it again later.';$('#skip').disabled=false;$('#undo').disabled=!last;}}
function answer(choice){if(!writer||!pairReady||busy||!active)return;if(Date.now()<voteAfter)return;voteAfter=Date.now()+500;busy=true;choiceEnabled(false);const t=active,v={left:t.left,right:t.right,leftHash:byId[t.left].imageHash,rightHash:byId[t.right].imageHash,choice:choice==='left'?t.left:choice==='right'?t.right:choice,undone:false,undoOf:null};put('choices',t.id,v);last={trial:t,eventId:state.drafts[slot('choices',t.id)].eventId};state.lastChoice=last;save();previous=t;renderBrief();showNext();}
function undo(){if(!writer||!last||busy)return;const {trial,eventId}=last,key=slot('choices',trial.id),d=state.drafts[key],r=state.records[key],sent=state.outbox.some(x=>x.event.eventId===eventId);
 if(d?.eventId===eventId&&!sent){delete state.drafts[key];changed();}
 else{const v=sent?state.outbox.find(x=>x.event.eventId===eventId).event.value:r?.eventId===eventId?r.value:null;if(!v){message('That choice has changed. Review the saved choice before undoing it.');return;}put('choices',trial.id,{...v,undone:true,undoOf:eventId});}
 last=null;state.lastChoice=null;save();skipped.delete(trial.id);showNext(trial);renderBrief();}
function compare(){for(const s of ['left','right']){const d=byId[$('#compare-'+s).value];if(!d)continue;$('#compare-'+s+'-image').src=d.image;$('#compare-'+s+'-image').alt=d.title;$('#compare-'+s+'-link').href=d.image;}}
function recipe(){return value('recipe','current')||{moves:[],note:''};}
function renderVocabulary(){if(!catalog)return;const r=recipe();$('#vocabulary').innerHTML=catalog.vocabulary.map(v=>`<article class="word"><h3>${esc(v.title)}</h3><p>${esc(v.description)}</p><button class="example" data-review="${v.example}">See the drawing ↗</button><button data-move="${v.id}" aria-pressed="${r.moves.includes(v.id)}" ${!writer?'disabled':''}>${r.moves.includes(v.id)?'Carry forward ✓':'Carry this forward'}</button></article>`).join('');}
function briefText(){if(!catalog)return '';const r=recipe(),lines=['ALL DOGS / NEXT DRAWINGS',r.note||'Develop the collection from the strongest existing drawings.','','COLLECTION DECISIONS'];
 for(const d of catalog.dogs){const v=review(d.id);if(v.verdict||v.note||v.parts.length){lines.push(`${d.number?'#'+d.number+' ':''}${d.title} [${d.kind}]: ${labels[v.verdict]||'Notes only'}`);if(v.parts.length)lines.push('Keep: '+v.parts.join(', '));if(v.note)lines.push(v.note);lines.push('Exact drawing: '+d.id);}}
 lines.push('','PARTICULAR COMPARISONS');for(const t of trials){const v=value('choices',t.id);if(v&&!v.undone){lines.push(t.question);lines.push(v.choice==='tie'?'About equal.':v.choice==='neither'?'Neither.':'Prefer '+byId[v.choice].title+' over '+byId[v.choice===v.left?v.right:v.left].title+'.');}}
 lines.push('','MOVES TO CARRY FORWARD');for(const m of catalog.vocabulary)if(r.moves.includes(m.id))lines.push(m.title+': '+m.description);
 lines.push('','Keep each comparison scoped to its question. A useful passage is not a whole-dog acceptance. Preserve the exact parents and source versions; prepare a short round of distinct drawings for review.');return lines.join('\n');}
function renderBrief(){if(!catalog)return;$('#intention').readOnly=!writer;if(document.activeElement!==$('#intention')){$('#intention').value=recipe().note;recipeBaseSeq=state.drafts[slot('recipe','current')]?.baseSeq??state.records[slot('recipe','current')]?.seq??0;}$('#brief').textContent=briefText();}
function describe(v){if(!v)return 'No saved version yet.';if('verdict' in v)return [labels[v.verdict]||'No whole-drawing decision',v.parts?.length?'Keep: '+v.parts.join(', '):'',v.note||''].filter(Boolean).join('\n');if('choice' in v)return (v.undone?'Undone: ':'')+(v.choice==='tie'?'About equal':v.choice==='neither'?'Neither':byId[v.choice]?.title||'Selected drawing');return [v.note||'',...(v.moves||[]).map(id=>catalog?.vocabulary.find(m=>m.id===id)?.title||id)].filter(Boolean).join('\n');}
function renderConflicts(){const entries=Object.entries(state.drafts).filter(([,d])=>d.conflict),box=$('#conflicts');if(!box)return;box.hidden=!entries.length;box.innerHTML=entries.map(([key,d])=>`<article><h3>Two versions of ${esc(byId[d.id]?.title||'this choice')}</h3><p>${d.value.undone?'This vote was replaced before it could be undone. Keep the saved choice, or review this comparison again.':esc(d.problem||'Your unsent version is preserved. Choose which version to keep.')}</p><b>Your version</b><pre>${esc(describe(d.value))}</pre><b>Saved version</b><pre>${esc(describe(state.records[key]?.value))}</pre><div class="buttons">${d.value.undone?`<button data-revisit="${d.id}">Review this pair again</button>`:`<button data-resolve="mine" data-key="${key}">Keep my version</button>`}<button data-resolve="saved" data-key="${key}">Use saved version</button></div></article>`).join('');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(!writer&&(b.dataset.verdict||b.dataset.part||b.dataset.move||b.dataset.resolve||b.dataset.revisit))return;if(b.dataset.revisit){resolve(state,slot('choices',b.dataset.revisit),false);changed();changeView('choices-view');showNext(trials.find(t=>t.id===b.dataset.revisit));return;}if(b.dataset.view)changeView(b.dataset.view);if(b.dataset.review)openReview(b.dataset.review);if(b.dataset.verdict){const id=b.dataset.dog,r=review(id);updateReview(id,{verdict:r.verdict===b.dataset.verdict?'':b.dataset.verdict});}if(b.dataset.part){const r=review(selected),p=b.dataset.part;updateReview(selected,{parts:r.parts.includes(p)?r.parts.filter(x=>x!==p):[...r.parts,p]});}if(b.dataset.move){const r=recipe(),m=b.dataset.move;put('recipe','current',{...r,moves:r.moves.includes(m)?r.moves.filter(x=>x!==m):[...r.moves,m]});renderVocabulary();renderBrief();}if(b.dataset.resolve){resolve(state,b.dataset.key,b.dataset.resolve==='mine');changed();renderWall();renderBrief();}});
$('#review-note').oninput=()=>{if(!writer||!selected)return;const key=slot('reviews',selected),had=!!state.drafts[key];updateReview(selected,{note:$('#review-note').value});if(!had){state.drafts[key].baseSeq=noteBaseSeq;save();}};$('#intention').oninput=()=>{if(!writer)return;const key=slot('recipe','current'),had=!!state.drafts[key];put('recipe','current',{...recipe(),note:$('#intention').value});if(!had){state.drafts[key].baseSeq=recipeBaseSeq;save();}renderBrief();};
['kind','decision'].forEach(id=>$('#'+id).onchange=()=>{limit=36;renderWall();});$('#search').oninput=()=>{limit=36;renderWall();};$('#more').onclick=()=>{limit+=36;renderWall();};$('#close-review').onclick=()=>$('#review').close();
$('#next-dog').onclick=()=>{const list=filtered(),i=list.findIndex(d=>d.id===selected);if(list.length)openReview(list[(i+1)%list.length].id);};$('#compare-parent').onclick=()=>{const d=byId[selected];$('#compare-left').value=d.parent;$('#compare-right').value=d.id;compare();$('#review').close();changeView('compare-view');};
$('#compare-left').onchange=compare;$('#compare-right').onchange=compare;$('#inspect-left').onclick=()=>openReview($('#compare-left').value);$('#inspect-right').onclick=()=>openReview($('#compare-right').value);
$('#choose-left').onclick=()=>answer('left');$('#choose-right').onclick=()=>answer('right');$('#tie').onclick=()=>answer('tie');$('#neither').onclick=()=>answer('neither');$('#undo').onclick=undo;$('#skip').onclick=()=>{if(busy||!active)return;skipped.add(active.id);previous=active;showNext();};$('#resume-skipped').onclick=()=>{skipped.clear();showNext();};
$('#connect').onclick=()=>{$('#connect-status').textContent=connected?'Connected. Your notes save privately on the art server.':'';$('#connection').showModal();};$('#sync-now').onclick=()=>{if(!connected){$('#connect-status').textContent='Enter your review key to connect.';return;}sync().then(()=>$('#connect-status').textContent='Up to date.').catch(e=>$('#connect-status').textContent=e.message);};$('#close-connect').onclick=()=>$('#connection').close();$('#connect-form').onsubmit=async e=>{e.preventDefault();if(!writer){$('#connect-status').textContent='Close the other collection tab before connecting here.';return;}const key=$('#review-key').value.trim();if(!key)return;try{localStorage.setItem('collection_token',key);localStorage.removeItem('collection_disconnected');await connect();$('#review-key').value='';$('#connection').close();}catch(e){connected=false;$('#connect').textContent='Connect feedback';$('#connect-status').textContent=e.message;}};$('#disconnect').onclick=()=>{connected=false;localStorage.removeItem('collection_token');localStorage.setItem('collection_disconnected','1');$('#connect').textContent='Connect feedback';message('Disconnected. Notes and unsent changes remain in this browser.');$('#connection').close();};
$('#export').onclick=()=>{const data={version:2,exportedAt:new Date().toISOString(),catalog:catalog.dogs.map(d=>({id:d.id,imageHash:d.imageHash,sourceHash:d.sourceHash,parent:d.parent})),feedback:state,brief:briefText()};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='all-dogs-collection-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};$('#copy-brief').onclick=async()=>{try{await navigator.clipboard.writeText(briefText());$('#copy-brief').textContent='Copied';}catch{$('#copy-brief').textContent='Select and copy the brief below';}};
window.addEventListener('online',()=>{if(connected)sync().catch(()=>{});});window.addEventListener('focus',()=>{if(connected)sync().catch(()=>{});});document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||$('#review').open||$('#connection').open||$('#choices-view').hidden)return;if(e.key==='1')answer('left');if(e.key==='2')answer('right');if(e.key==='3')answer('tie');if(e.key==='4')answer('neither');if(e.key.toLowerCase()==='z')undo();});
try{const r=await fetch('catalog.json',{cache:'no-cache'});if(!r.ok)throw Error('The dog catalog could not load.');catalog=await r.json();byId=Object.fromEntries(catalog.dogs.map(d=>[d.id,d]));trials=catalog.rounds[0].trials;$('#round-title').textContent=catalog.rounds[0].title;const opts=catalog.dogs.map(d=>`<option value="${d.id}">${d.number?'#'+d.number+' ':''}${esc(d.title)}${d.kind==='study'?' · study':''}</option>`).join('');$('#compare-left').innerHTML=opts;$('#compare-right').innerHTML=opts;$('#compare-left').value=catalog.dogs.find(d=>d.number===62).id;$('#compare-right').value=catalog.dogs.find(d=>d.prop==='pocket_knife').id;renderWall();renderVocabulary();renderBrief();compare();message(storage?'Choose the originals to keep. Connect feedback to save privately on your server.':'Browser storage unavailable. Connect feedback before reviewing.');claimWriter();}catch(e){$('#error').hidden=false;$('#error').textContent=e.message+' Reload or use Connect feedback to retry.';}

function claimWriter(){if(!navigator.locks){$('#save-status').textContent='This browser cannot coordinate saved feedback. Open the collection in a current browser to edit.';return;}navigator.locks.request('all-dogs-collection-editor',async()=>{try{const fresh=JSON.parse(localStorage.getItem(KEY)||'null');if(fresh?.version===2)state=fresh;}catch{}last=state.lastChoice||null;writer=true;renderWall();renderVocabulary();renderBrief();renderConflicts();if(selected&&$('#review').open)openReview(selected);if(active)choiceEnabled(pairReady);message('Your collection feedback is ready. Connect to save privately on your server.');if(token()){try{await connect();}catch(e){message(e.message);}}await new Promise(()=>{});}).catch(()=>message('Feedback editing could not start. Reload this page.'));}
window.addEventListener('storage',e=>{if(e.key!==KEY||writer||!e.newValue)return;try{const fresh=JSON.parse(e.newValue);if(fresh.version!==2)return;state=fresh;last=state.lastChoice||null;if(catalog){renderWall();renderVocabulary();renderBrief();renderConflicts();if(selected&&$('#review').open)openReview(selected);updateChoiceCount();}}catch{}});
